# Generated by Django 2.2.17 on 2021-01-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210109_0044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operator',
            new_name='Catalogue',
        ),
        migrations.RenameField(
            model_name='cataloguemetadata',
            old_name='operator',
            new_name='catalogue',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='operator',
            new_name='catalogue',
        ),
    ]
