# Generated by Django 2.2.17 on 2021-01-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloguemetadata',
            name='rel',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cataloguemetadata',
            name='val',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itemmetadata',
            name='rel',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itemmetadata',
            name='val',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mode',
            name='long_desc',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='RelValPair',
        ),
    ]
